server:
  port: ${PORT:8081}
spring:
  application:
    name: greeting-ui
  sleuth:
    sampler:
      percentage: 1.0 #100%
  zipkin:
    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411}
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
    